server:
  port: 8081
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/project1}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
